stash_yum_baseurl: https://stash-stage.pennstatehealth.net/yum/7
stash_username: ansible-stage
stash_password: '{{ vault_stash_password }}'

db_host: psh01com4biodb1.pennstatehealth.net
db_name: bioatlas
db_username: bioatlas
db_password: '{{ vault_db_password }}'
db_admin_username: bioatlas-admin
db_admin_password: '{{ vault_db_admin_password }}'

mysql_host: psh01com4biodb1.pennstatehealth.net
mysql_port: 3306
mysql_db: bioatlas
mysql_user: bioatlas
mysql_pass: '{{ vault_user_pass }}'
mysql_admin: bioatlas-admin
mysql_admin_pass: '{{ vault_admin_pass }}'

mellon_fqdn: bioatlas-stage.pennstatehealth.net
mellon_domain: pennstatehealth.net


ssl_only: true
crt_private_key: '{{ vault_crt_private_key }}'
db_ca_path: /data/php/bioatlas/bioatlas/zfatlasDump/ca.pem
db_ca: |
    -----BEGIN CERTIFICATE-----
    MIIIOTCCByGgAwIBAgIRAKh+sJcGPwLNntBYNRCfefYwDQYJKoZIhvcNAQELBQAwdjELMAkGA1UE
    BhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3IxEjAQBgNVBAoTCUludGVybmV0
    MjERMA8GA1UECxMISW5Db21tb24xHzAdBgNVBAMTFkluQ29tbW9uIFJTQSBTZXJ2ZXIgQ0EwHhcN
    MTkxMDAzMDAwMDAwWhcNMjExMDAyMjM1OTU5WjCB3DELMAkGA1UEBhMCVVMxDjAMBgNVBBETBTE2
    ODAyMRUwEwYDVQQIEwxQZW5uc3lsdmFuaWExGDAWBgNVBAcTD1VuaXZlcnNpdHkgUGFyazEVMBMG
    A1UECRMMMjAxIE9sZCBNYWluMSowKAYDVQQKEyFUaGUgUGVubnN5bHZhbmlhIFN0YXRlIFVuaXZl
    cnNpdHkxGzAZBgNVBAsTElBlbm4gU3RhdGUgSGVyc2hleTEsMCoGA1UEAxMjcHNoMDFjb200Ymlv
    ZGIxLnBlbm5zdGF0ZWhlYWx0aC5uZXQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCo
    RBLpza+oPZ+V3gOfFXEZqTTRzAuAe38nRCZE3uLhy/Z3/0VKCKYCB91E2CTjORlP+C0POlp/4JAp
    Zz6DL0kEjZuENuihSyrl7LRj/cahAY1zGANnw8UnX7bmuG8NBhdsHuYTnFLB0emFIomMmLEwMR1f
    i+teagHsQ85/k+UOhf9ScwiPyGiCCq8YbbfCESCwET9cxoG1EvUTGC7+3ABmKhX5/j5hMOtlkdYo
    ++EGitK8nhSm8hghsFun2ioEa49JDtZeWEtiGGbFcP0a2ft+Kn6rFxGHIOqf49NLVb+sSZV2PHN9
    zKyrJ8Ha88VGsQkRRWvmB5jxbqtnHw/FPVbnNrZqJOTn8dyAxyW8memQcMaNg79mkhk0FQDQPPEh
    5+WCj3Jq6OP8F04qc/0eRsaHXAa2m9Bj092suYBln88rdhJ4AemuxgK7jz5srqndnEL7ZMacKTgR
    MZInMFfhsXhmi8wb0X3yovfx+t+gUs/7fuYMl6zbIibtZTgyHg5yjyk56FQvLBwzi+K2PFvjpQiI
    sXMhtTu1fSygNBFrHUOc6Dkuy6LA2hX8zS+1f22r1E8ChGuiUgUtiHkZxvBroExYGy4ug+ns+Ocq
    Q0Fj040fptFGdYLjNkQIwswo+YzkOiNZQXFh/0Vb9mlqN5rj4k37i6jiPnMQ0q4ZpVzkykoLeQID
    AQABo4IDWTCCA1UwHwYDVR0jBBgwFoAUHgWjd49sluJbh0umtIascQAM5zgwHQYDVR0OBBYEFNZK
    368Ha/5q0YSX2qq+3llESuQqMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQW
    MBQGCCsGAQUFBwMBBggrBgEFBQcDAjBnBgNVHSAEYDBeMFIGDCsGAQQBriMBBAMBATBCMEAGCCsG
    AQUFBwIBFjRodHRwczovL3d3dy5pbmNvbW1vbi5vcmcvY2VydC9yZXBvc2l0b3J5L2Nwc19zc2wu
    cGRmMAgGBmeBDAECAjBEBgNVHR8EPTA7MDmgN6A1hjNodHRwOi8vY3JsLmluY29tbW9uLXJzYS5v
    cmcvSW5Db21tb25SU0FTZXJ2ZXJDQS5jcmwwdQYIKwYBBQUHAQEEaTBnMD4GCCsGAQUFBzAChjJo
    dHRwOi8vY3J0LnVzZXJ0cnVzdC5jb20vSW5Db21tb25SU0FTZXJ2ZXJDQV8yLmNydDAlBggrBgEF
    BQcwAYYZaHR0cDovL29jc3AudXNlcnRydXN0LmNvbTAuBgNVHREEJzAlgiNwc2gwMWNvbTRiaW9k
    YjEucGVubnN0YXRlaGVhbHRoLm5ldDCCAX4GCisGAQQB1nkCBAIEggFuBIIBagFoAHUAfT7y+I//
    iFVoJMLAyp5SiXkrxQ54CX8uapdomX4i8NcAAAFtkepjDgAABAMARjBEAiBRfiRLVSkVl/KYXNfW
    1qqXdDLD5hihs1fsYF0gb5HMQQIgCBnPVFKk6KH3DC18evSo8NYbyPiQGLTXVOChwrE9+fQAdwBE
    lGUusO7Or8RAB9io/ijA2uaCvtjLMbU/0zOWtbaBqAAAAW2R6mL4AAAEAwBIMEYCIQDx2VLdaeHr
    KO1gNCm56nqdAydZmGivUneV/u2D4FG6bwIhAMDmWLan1D7eDWyq4E4oo8PhyUWwX12CzS2twYce
    b/0fAHYAVYHUwhaQNgFK6gubVzxT8MDkOHhwJQgXL6OqHQcT0wwAAAFtkepjLAAABAMARzBFAiAw
    JuhbpbhKwlLzLZYbwJN211L/e+8hsmwGnn/82jCkKgIhAM9g/NmiBNzXR3OgpN5SXs7xdutjVfo1
    4XVSroiRxfKvMA0GCSqGSIb3DQEBCwUAA4IBAQA9bKPyTCFbCuIy370V7LRYMDhYE4bug2U6FfjZ
    lODhakm3vUAHXDIpeHRKfX3ftx1vxveE/Z3sAjzGPCXZWVEXXGz7UQl7Vifl9nvIAjRQrn3QgLEH
    XCDGHQFeC6ix9u3IrvLqW83QFm6Ih1+f7etXKzXzE3i6SuDlH199ivt3rnDjwlUmJQoknxxGzoEX
    SdWIDcBvZrk3KZf5qv790D+rdIgtGqxAqz0zYR83mktLaxlw/zhkNteO1SY77UksaQIr/XuT59Ct
    MXUacTqUCRZ7DDbwlwlM6SY0wHaKNOl9VAq2JWCFhmoFHcpxVXVYJBOvoGn3ZahjSK/etb1KtlE+
    -----END CERTIFICATE-----
crt: |
  -----BEGIN CERTIFICATE-----
  MIIIIzCCBougAwIBAgIQVPmwozY1kwvxhG9kwTVHLjANBgkqhkiG9w0BAQwFADBE
  MQswCQYDVQQGEwJVUzESMBAGA1UEChMJSW50ZXJuZXQyMSEwHwYDVQQDExhJbkNv
  bW1vbiBSU0EgU2VydmVyIENBIDIwHhcNMjQwNTAzMDAwMDAwWhcNMjUwNTAzMjM1
  OTU5WjB+MQswCQYDVQQGEwJVUzEVMBMGA1UECBMMUGVubnN5bHZhbmlhMSowKAYD
  VQQKEyFUaGUgUGVubnN5bHZhbmlhIFN0YXRlIFVuaXZlcnNpdHkxLDAqBgNVBAMT
  I3BzaDAxY29tNGJhdGxhcy5wZW5uc3RhdGVoZWFsdGgubmV0MIICIjANBgkqhkiG
  9w0BAQEFAAOCAg8AMIICCgKCAgEAiipxNgVZXssGFriYyz7RoCIUFaiAL0g4t6Ek
  ww18LYCKrXwDku2ud3UTLhfCPmGT1FBxnTOyfxTCZnzzb7NMp7+FD+5Ejgb+7o2U
  ikCkmnUxxsLKEQjBVlZwsp4aHJMQCzdimwW7lBx3uSCWfQt+vIwWVlJAVcvrvPv3
  3SsVkf7myWeE269YjV1LOEV6fxyvndS3LxWVw5K26w7dW5hFK8B3iWLCqJBEvcmx
  7Okjxg38zNDKsDYx2dQyAYusxnA7UfOfp4bfwmxqtMLNvQpKOuT9DfZmdDfUcAuf
  tTMEgxNkpnwHjfKU92yEdLl26BRENTHvdR7/upFKJfTieQMsg2zNsjFQyJAgPvup
  EJrEFz/3F7S9eRshOTncifHwikRqcv1ins9mLBMtEdruwzZUbJiF4GbcSz2uiQ/E
  AGnZiqQPZGSttSWEwWEcsrdbzDaf3Tsj9wuUXNJn+qPAaKsqIOsZvEOci/Pktw51
  hSiEN9PXWPL/bnqy/9XWzzbH2HNRlFn/5bz5R83RmYAHad8B1Pd9IdCJhyBb6PNR
  MmlUByVW9FUors6YFxff0r61jw+gPc1uRLKGgdtad2nmg1EzuQNPFjysLHGBuCY0
  ShIb7Hsa+norPmmUn+aj0HqLLW0+72YqvyLk5Z8cFakcnCTorYHbo+dF5N7l0e83
  rP51jIcCAwEAAaOCA1UwggNRMB8GA1UdIwQYMBaAFO9MAJKm+3YuXpXiyV+HGxnV
  TeLZMB0GA1UdDgQWBBStw/MBa8xUZ45HkR/Tf3UH75372TAOBgNVHQ8BAf8EBAMC
  BaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
  SQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICZzAlMCMGCCsGAQUFBwIBFhdodHRwczov
  L3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgIwQAYDVR0fBDkwNzA1oDOgMYYvaHR0
  cDovL2NybC5zZWN0aWdvLmNvbS9JbkNvbW1vblJTQVNlcnZlckNBMi5jcmwwcAYI
  KwYBBQUHAQEEZDBiMDsGCCsGAQUFBzAChi9odHRwOi8vY3J0LnNlY3RpZ28uY29t
  L0luQ29tbW9uUlNBU2VydmVyQ0EyLmNydDAjBggrBgEFBQcwAYYXaHR0cDovL29j
  c3Auc2VjdGlnby5jb20wggF9BgorBgEEAdZ5AgQCBIIBbQSCAWkBZwB1AM8RVu7V
  Lnyv84db2Wkum+kacWdKsBfsrAHSW3fOzDsIAAABjz8QFqAAAAQDAEYwRAIgalJg
  LSJF3/P0lG1/jTM+RzTUKum34e6pNRBxt48PODcCIDpoDq85PuLXGDmZYwmKkfop
  nYEuUeuvSS2fkx6681jQAHYAouMK5EXvva2bfjjtR2d3U9eCW4SU1yteGyzEuVCk
  R+cAAAGPPxAWfQAABAMARzBFAiEAlIz9zycdaupY7YAsvT2eTCFHFs18qRl1bBvR
  ASyZ8LgCIEmHLiqi2ge1557c3DeW2yXXksgjo9IMtWRSRZcJ86LhAHYATnWjJ1ya
  EMM4W2zU3z9S6x3w4I4bjWnAsfpksWKaOd8AAAGPPxAWfQAABAMARzBFAiBdHOIO
  1hBvMgrmoMNkzsWunalcsooqV9CgpF08LVT/pAIhAKz3tEYDbcy9pNAHctikTd0v
  Ro9sf1WXUxMeOpy1f6n0MFIGA1UdEQRLMEmCI3BzaDAxY29tNGJhdGxhcy5wZW5u
  c3RhdGVoZWFsdGgubmV0giJiaW9hdGxhcy1zdGFnZS5wZW5uc3RhdGVoZWFsdGgu
  bmV0MA0GCSqGSIb3DQEBDAUAA4IBgQBDHibz96W3Bt1LtAatugJF4msrZOBSrEKD
  bPJotLs9G3AHv+1XEAyRzeDDCi7FWGA0syW0Wssu2+N2dsG02pdj6ECI+ewl8Izw
  W5e3yl5D+ouEDFAVbXOAU7TUB18q9VNwVoNqrmEwIX3qr44LWbD/a8LCtuU6SY0s
  lSjhHl8iVr+icL3MGqf33XRWfN8L+wVyDo2yPdfcfuuBWlnJEAdKdizuL06MuyAN
  nAK03qolrb0yii7qc3Rph2RgEAHe7Xt7mnfsTacfPMsoJqX5UULKr6Z6Pb3yVRly
  G9GdNahWbWejkXLbNtajl8mOmd6hzGgJW2kanRo9Sn07atbgsy7rEqHH2RzYG+1J
  9tCf/Q+gZkcsHdBPYXNAvXp7t9pUafHsvFkCVGi1OM9HZjdUO6N369HdHd0bd+Z8
  yvt2T3jaExHu9FoVLYVvj1o/p1V98Q6Q/o8+spqvjlvtbdD5o1jXfKf0CABq1JrW
  Xr00dSOYKHLimH8UVt6/4IVwAL8Yu88=
  -----END CERTIFICATE-----

crt_chain: |
  -----BEGIN CERTIFICATE-----
  MIIEMjCCAxqgAwIBAgIBATANBgkqhkiG9w0BAQUFADB7MQswCQYDVQQGEwJHQjEb
  MBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHDAdTYWxmb3JkMRow
  GAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UEAwwYQUFBIENlcnRpZmlj
  YXRlIFNlcnZpY2VzMB4XDTA0MDEwMTAwMDAwMFoXDTI4MTIzMTIzNTk1OVowezEL
  MAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE
  BwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNVBAMM
  GEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczCCASIwDQYJKoZIhvcNAQEBBQADggEP
  ADCCAQoCggEBAL5AnfRu4ep2hxxNRUSOvkbIgwadwSr+GB+O5AL686tdUIoWMQua
  BtDFcCLNSS1UY8y2bmhGC1Pqy0wkwLxyTurxFa70VJoSCsN6sjNg4tqJVfMiWPPe
  3M/vg4aijJRPn2jymJBGhCfHdr/jzDUsi14HZGWCwEiwqJH5YZ92IFCokcdmtet4
  YgNW8IoaE+oxox6gmf049vYnMlhvB/VruPsUK6+3qszWY19zjNoFmag4qMsXeDZR
  rOme9Hg6jc8P2ULimAyrL58OAd7vn5lJ8S3frHRNG5i1R8XlKdH5kBjHYpy+g8cm
  ez6KJcfA3Z3mNWgQIJ2P2N7Sw4ScDV7oL8kCAwEAAaOBwDCBvTAdBgNVHQ4EFgQU
  oBEKIz6W8Qfs4q8p74Klf9AwpLQwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
  MAMBAf8wewYDVR0fBHQwcjA4oDagNIYyaHR0cDovL2NybC5jb21vZG9jYS5jb20v
  QUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNqA0oDKGMGh0dHA6Ly9jcmwuY29t
  b2RvLm5ldC9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDANBgkqhkiG9w0BAQUF
  AAOCAQEACFb8AvCb6P+k+tZ7xkSAzk/ExfYAWMymtrwUSWgEdujm7l3sAg9g1o1Q
  GE8mTgHj5rCl7r+8dFRBv/38ErjHT1r0iWAFf2C3BUrz9vHCv8S5dIa2LX1rzNLz
  Rt0vxuBqw8M0Ayx9lt1awg6nCpnBBYurDC/zXDrPbDdVCYfeU0BsWO/8tqtlbgT2
  G9w84FoVxp7Z8VlIMCFlA2zs6SFz7JsDoeA3raAVGI/6ugLOpyypEBMs1OUIJqsi
  l2D4kF501KKaU73yqWjgom7C12yxow+ev+to51byrvLjKzg6CYG1a4XXvi3tPxq3
  smPi9WIsgtRqAEFQ8TmDn5XpNpaYbg==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7
  MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD
  VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE
  AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4
  MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
  MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO
  ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0
  aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sI
  s9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnG
  vDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQ
  Ijy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfb
  IWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0
  tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97E
  xwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNV
  icQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5
  D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJ
  WBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ
  5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzG
  KAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSg
  EQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rID
  ZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAG
  BgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29t
  L0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggr
  BgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUA
  A4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+
  rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+
  /czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gA
  CiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1F
  zZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyA
  vGp4z7h/jnZymQyd/teRCBaho1+V
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIGSjCCBDKgAwIBAgIRAINbdhUgbS1uCX4LbkCf78AwDQYJKoZIhvcNAQEMBQAw
  gYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5MRQwEgYDVQQHEwtK
  ZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4wLAYD
  VQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTIy
  MTExNjAwMDAwMFoXDTMyMTExNTIzNTk1OVowRDELMAkGA1UEBhMCVVMxEjAQBgNV
  BAoTCUludGVybmV0MjEhMB8GA1UEAxMYSW5Db21tb24gUlNBIFNlcnZlciBDQSAy
  MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAifBcxDi60DRXr5dVoPQi
  Q/w+GBE62216UiEGMdbUt7eSiIaFj/iZ/xiFop0rWuH4BCFJ3kSvQF+aIhEsOnuX
  R6mViSpUx53HM5ApIzFIVbd4GqY6tgwaPzu/XRI/4Dmz+hoLW/i/zD19iXvS95qf
  NU8qP7/3/USf2/VNSUNmuMKlaRgwkouue0usidYK7V8W3ze+rTFvWR2JtWKNTInc
  NyWD3GhVy/7G09PwTAu7h0qqRyTkETLf+z7FWtc8c12f+SfvmKHKFVqKpNPtgMkr
  wqwaOgOOD4Q00AihVT+UzJ6MmhNPGg+/Xf0BavmXKCGDTv5uzQeOdD35o/Zw16V4
  C4J4toj1WLY7hkVhrzKG+UWJiSn8Hv3dUTj4dkneJBNQrUfcIfTHV3gCtKwXn1eX
  mrxhH+tWu9RVwsDegRG0s28OMdVeOwljZvYrUjRomutNO5GzynveVxJVCn3Cbn7a
  c4L+5vwPNgs04DdOAGzNYdG5t6ryyYPosSLH2B8qDNzxAgMBAAGjggFwMIIBbDAf
  BgNVHSMEGDAWgBRTeb9aqitKz1SA4dibwJ3ysgNmyzAdBgNVHQ4EFgQU70wAkqb7
  di5eleLJX4cbGdVN4tkwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8C
  AQAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMCIGA1UdIAQbMBkwDQYL
  KwYBBAGyMQECAmcwCAYGZ4EMAQICMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9j
  cmwudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9y
  aXR5LmNybDBxBggrBgEFBQcBAQRlMGMwOgYIKwYBBQUHMAKGLmh0dHA6Ly9jcnQu
  dXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FBQUFDQS5jcnQwJQYIKwYBBQUHMAGG
  GWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggIBACaA
  DTTkHq4ivq8+puKE+ca3JbH32y+odcJqgqzDts5bgsapBswRYypjmXLel11Q2U6w
  rySldlIjBRDZ8Ah8NOs85A6MKJQLaU9qHzRyG6w2UQTzRwx2seY30Mks3ZdIe9rj
  s5rEYliIOh9Dwy8wUTJxXzmYf/A1Gkp4JJp0xIhCVR1gCSOX5JW6185kwid242bs
  Lm0vCQBAA/rQgxvLpItZhC9US/r33lgtX/cYFzB4jGOd+Xs2sEAUlGyu8grLohYh
  kgWN6hqyoFdOpmrl8yu7CSGV7gmVQf9viwVBDIKm+2zLDo/nhRkk8xA0Bb1BqPzy
  bPESSVh4y5rZ5bzB4Lo2YN061HV9+HDnnIDBffNIicACdv4JGyGfpbS6xsi3UCN1
  5ypaG43PJqQ0UnBQDuR60io1ApeSNkYhkaHQ9Tk/0C4A+EM3MW/KFuU53eHLVlX9
  ss1iG2AJfVktaZ2l/SbY7py8JUYMkL/jqZBRjNkD6srsmpJ6utUMmAlt7m1+cTX8
  6/VEBc5Dp9VfuD6hNbNKDSg7YxyEVaBqBEtN5dppj4xSiCrs6LxLHnNo3rG8VJRf
  NVQdgFbMb7dOIBokklzfmU69lS0kgyz2mZMJmW2G/hhEdddJWHh3FcLi2MaeYiOV
  RFrLHtJvXEdf2aEaZ0LOb2Xo3zO6BJvjXldv2woN
  -----END CERTIFICATE-----

#gitlab_runner_authorized_keys: |
#  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC75h45u0xT+MV3XGCAAznRDy55pgoSmmKU+c4Zur1Dv9EAVkUrYGGps36gJaAv1cb30KICH+jOAm58BMAg0Y61gT6XwatGDjMl0Ftqf1dd76UDifzrJ/VXadyxLrDFVc1plPxJMkM2vRYfRE4FAF4E0SEHa7PCBNRpbUkIL9GeL7rKVtlkS+PiZpQCcRr6WBrKKze3Zsmd4unMDBGSe3XOtBxpkjYsUtWAQSj9y9uMhPKSTZja/cWN/fZIbCTMTH0KHrAcgONPToqbuLtV/lJ9iUVDU7YIu6wSmNrjJb0zResPrp/ksH55Lnaw5gblRblD6UjAOMzwnu3WKXFN/YAv research_informatics@toolchest.med.psu.edu

#gitlab_runner_wheel: true
#gitlab_runner_password: '{{ vault_gitlab_runner_password }}'

ansible_become_pass: '{{ vault_ansible_sudo_pass }}'
